name: brickinv

services:
  mariadb:
    image: mariadb:11.2.2-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 'wN%F3doRGFnh25MJ*D^N*vp*oV9ybp^zAwMkZaS%B3!yhsxv!#Kn@PCpo76zLRyu6EL#2$n8BzXpM&u*@h*kiVwY3m!5nUmf2VmMUmSVYm*bv48q2&pUKsRVe*Pe*9Yp'
    volumes:
      - "mariadb:/var/lib/mysql"
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"

  frontend:
    image: ghcr.io/bennetrr/brickinv-frontend:0.0.0
    restart: always
    networks:
      - reverse_proxy
    volumes:
      - "./env.js:/usr/share/nginx/html/env/env.js"

  backend:
    image: ghcr.io/bennetrr/brickinv-backend:0.0.0
    restart: always
    env_file:
      - backend.env
    networks:
      - reverse_proxy
    links:
      - mariadb

networks:
  reverse_proxy:
    external: true

volumes:
  mariadb:
