version: '3.8'

services:
  pocketBase:
    build:
      context: .
      dockerfile: pocketBase.Dockerfile
    image: bennetrr/lego:pocketBase
    container_name: lego-pocketBase
    restart: always
    ports:
      - "8200:8080"

  svelteApp:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: bennetrr/lego:svelteApp
    container_name: lego-svelteApp
    restart: always
    ports:
      - "8201:5000"
