version: '3.8'

volumes:
  pocketbase_data:

services:
  pocketbase:
    image: ghcr.io/bennetrr/lego-pocketbase:latest
    container_name: lego-pocketBase
    restart: always
    ports:
      - "8200:8080"
    volumes:
      - type: volume
        source: pocketbase_data
        target: /pb/

  app:
    image: ghcr.io/bennetrr/lego-app:latest
    container_name: lego-app
    restart: always
    ports:
      - "8201:80"
