version: '3.8'

volumes:
  lego-pocketbase-data:

services:
  pocketbase:
    image: bennetrr/lego-pocketbase
    container_name: lego-pocketBase
    restart: always
    ports:
      - "8200:8080"
    volumes:
      - type: volume
        source: lego-pocketbase-data
        target: "/pb/"

    build:
      context: .
      dockerfile: pocketbase.Dockerfile
