name: brickinv

services:
  mariadb:
    image: mariadb:11.6.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "brickinv"
    volumes:
      - "mariadb:/var/lib/mysql"
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    networks:
      - internal

  redis:
    image: redis:7.4.1-alpine
    restart: always
    networks:
      - internal

  frontend:
    image: ghcr.io/bennetrr/brickinv-frontend:0.0.0
    restart: always
    networks:
      - reverse_proxy
    volumes:
      - "./env.js:/usr/share/nginx/html/env/env.js"

  backend:
    image: ghcr.io/bennetrr/brickinv-backend:0.0.0
    restart: always
    env_file:
      - backend.env
    networks:
      - reverse_proxy
      - internal

networks:
  internal:
  reverse_proxy:
    external: true

volumes:
  mariadb:
