name: bennetr-brickinv

services:
  mariadb:
    image: mariadb:11.2.2-jammy
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    volumes:
      - "mariadb:/var/lib/mysql"
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - 3306:3306
  
  frontend:
    image: ghcr.io/bennetrr/brickinv-frontend:0.0.0
    
  backend:
    image: ghcr.io/bennetrr/brickinv-backend:0.0.0

volumes:
    mariadb:
