name: Build and push container
description: Build and optionally push a container image

inputs:
  registry-server:
    description: Container registry server
    required: false
    default: docker.io
  registry-user:
    description: Container registry username
    required: false
  registry-password:
    description: Container registry password
    required: false
  name:
    description: Name of the container image
    required: true
  version:
    description: Version of the container image (with prefix)
    required: true
  file:
    description: Path to Dockerfile
    required: false
  context:
    description: Working / context directory for the build process (without trailing slash)
    required: false
    default: .
  push:
    description: Whether to push the container image to the registry
    required: true
    default: 'false'
  wemogy-npm-server:
    description: wemogy npm proxy server
    required: false
  wemogy-npm-user:
    description: wemogy npm proxy username
    required: false
  wemogy-npm-password:
    description: wemogy npm proxy password
    required: false

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to container registery
      uses: docker/login-action@v3
      if: ${{ inputs.push == 'true' }}
      with:
        registry: ${{ inputs.registry-server }}
        username: ${{ inputs.registry-user }}
        password: ${{ inputs.registry-password }}

    - name: Build ${{ inputs.push && 'and push ' }}container
      uses: docker/build-push-action@v5
      with:
        tags: ${{ inputs.registry-server }}/${{ inputs.name }}:${{ inputs.version }}
        file: ${{ inputs.file }}
        context: ${{ inputs.context }}
        push: ${{ inputs.push }}
        platforms: linux/amd64,linux/arm64
        build-args: |
          WEMOGY_NPM_SERVER=${{ inputs.wemogy-npm-server }}
          WEMOGY_NPM_USER=${{ inputs.wemogy-npm-user }}
          WEMOGY_NPM_PASSWORD=${{ inputs.wemogy-npm-password }}
