// This file is automatically generated by Cosmos. Add it to .gitignore and
// only edit if you know what you're doing.

import { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

export const rendererConfig: RendererConfig = {
  "playgroundUrl": "http://localhost:5001",
  "rendererUrl": "http://localhost:5050"
};

const fixtures = {};

const decorators = {};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
