name: Merge multiarch container
description: Merge container images for multiple args and push them to the registry

inputs:
  registry-server:
    description: Container registry server
    required: false
  registry-user:
    description: Container registry username
    required: false
  registry-password:
    description: Container registry password
    required: false
  name:
    description: Name of the container image
    required: false
    default: 'some-image'
  version:
    description: Version of the container image (with prefix)
    required: false
    default: 'v0.0.0'

runs:
  using: composite
  steps:
    - name: Prepare
      run: |
        registry_image=${{ inputs.registry-server }}/${{ inputs.name }}
        echo "REGISTRY_IMAGE=$registry_image" >> $GITHUB_ENV
        echo "FULL_IMAGE_NAME=${registry_image//\//-}" >> $GITHUB_ENV
      shell: bash

    - name: Download digests
      uses: actions/download-artifact@v4
      with:
        path: /tmp/digests
        pattern: digests-${{ env.FULL_IMAGE_NAME }}-*
        merge-multiple: true

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY_IMAGE }}
        flavor: |
          latest=false
        tags: |
          type=raw,value=${{ inputs.version }}
          type=sha

    - name: Set up buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry-server }}
        username: ${{ inputs.registry-user }}
        password: ${{ inputs.registry-password }}

    - name: Create manifest list and push
      working-directory: /tmp/digests
      run: |
        docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
      shell: bash
