name: Test build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  container-frontend:
    name: Build frontend container
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { docker: linux/amd64 }
          - { docker: linux/arm64 }
          - { docker: linux/arm64/v8 }
    steps:
      - uses: actions/checkout@v4

      - name: Build container
        uses: ./.github/actions/containers/build
        with:
          push: 'false'
          context: src/frontend
          docker-platform: ${{ matrix.platform.docker }}

  container-backend:
    name: Build backend container
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { docker: linux/amd64, dotnet: amd64, dotnet-ef: linux-x64 }
          - { docker: linux/arm64, dotnet: arm64, dotnet-ef: linux-arm64 }
          - { docker: linux/arm64/v8, dotnet: arm64, dotnet-ef: linux-arm64 }
    steps:
      - uses: actions/checkout@v4

      - name: Build container
        uses: ./.github/actions/containers/build
        with:
          push: 'false'
          context: src/backend/
          docker-platform: ${{ matrix.platform.docker }}
          dotnet-platform: ${{ matrix.platform.dotnet }}
          dotnet-ef-platform: ${{ matrix.platform.dotnet-ef }}
