name: Lint

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  prettier:
    name: Lint frontend with prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run prettier
        working-directory: src/frontend
        run: |
          npx prettier --check .

  eslint:
    name: Lint frontend with eslint
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      pull-requests: write
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.4.1
        with:
          package_json_file: src/frontend/package.json

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: src/frontend/package.json
          cache-dependency-path: src/frontend/pnpm-lock.yaml
          cache: pnpm

      - name: Install dependencies
        working-directory: src/frontend
        run: |
          pnpm install --frozen-lockfile

      - name: Run eslint
        working-directory: src/frontend
        run: |
          pnpm lint --format json --output-file result.json

      - name: Upload eslint results
        if: always()
        uses: ldiego73/eslint-report-action@v1.1
        with:
          report: src/frontend/result.json
