name: Lint

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  editorconfig:
    name: Lint with editorconfig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run eclint
        run: |
          npx eclint check .

  eslint:
    name: Lint frontend with eslint
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          package_json_file: src/frontend/package.json

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: src/frontend/package.json
          cache-dependency-path: src/frontend/pnpm-lock.yaml
          cache: 'pnpm'

      - name: Authenticate to wemogy npm proxy
        run: pnpx npm-cli-login
        env:
          NPM_REGISTRY: ${{ secrets.WEMOGY_NPM_SERVER }}
          NPM_USER: ${{ secrets.WEMOGY_NPM_USER }}
          NPM_PASS: ${{ secrets.WEMOGY_NPM_PASSWORD }}
          NPM_EMAIL: it@wemogy.com
          NPM_SCOPE: "@wemogy"

      - name: Install dependencies
        working-directory: src/frontend
        run: |
          pnpm install

      - name: Run eslint
        uses: sibiraj-s/action-eslint@2e3213f837c945a07368d53e42f4c16453c02087
        with:
          working-directory: src/frontend
          token: ${{ secrets.GITHUB_TOKEN }}
          all-files: true
          eslint-args: '--ignore-path=src/frontend/.gitignore --report-unused-disable-directives --max-warnings 0'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
          use-npx: true
