name: Lint

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  editorconfig:
    name: Lint with editorconfig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run eclint
        run: |
          npx eclint check .
